---
- hosts: kafkaserver
  become: true
  roles:
    - ./../roles/docker
    - ./../roles/docker_containers
  tasks:
    - name: Trigger Build & Run
      shell: echo "Running build"
      notify:
        - docker stop containers
        - docker remove containers
        - docker run kafka
