- name: Grab Docker Install Script
  get_url:
    url: https://get.docker.com
    dest: /tmp/get-docker.sh
    mode: 0755
  notify: exec docker script

- name: Verify Docker Command
  shell: command -v docker >/dev/null 2>&1
  ignore_errors: true
  register: docker_exists

- debug: msg=”{{ docker_exists.rc }}”

- name: Run docker install script if docker not running
  shell: /tmp/get-docker.sh
  when: docker_exists.rc != 0
