- name: docker stop containers
  shell: docker stop $(docker ps -aq)
  when: containers_running.rc == 0
  ignore_errors: true
- name: docker remove containers
  shell: docker rm $(docker ps -aq)
  when: containers_running.rc == 0
  ignore_errors: true
- name: docker run nginx lb
  vars:
    - _nginx_lb_path: /etc/nginx/conf.d/default.conf
  shell: |
    docker run \
    --restart always \
    -v {{ nginx_lb_conf_path | default(_nginx_lb_path) }}:/etc/nginx/conf.d/default.con-
    f:ro \
    -p 80:80 \
    -d nginx

- name: docker build
  vars:
    _docker_app_name: app
  shell:
    cmd: docker build -f Dockerfile -t "{{ docker_app_name | default(_docker_app_name) }}" .
    chdir: '{{ dest_dir }}'
- name: docker run app
  vars:
    _docker_app_name: app
  shell: |
    docker run \
    --restart always \
    -p 3000:3000 \
    -e PORT=3000 \
    -d "{{ docker_app_name | default(_docker_app_name) }}"
