- name: docker stop containers
  shell: docker stop $(docker ps -aq)
  when: containers_running.rc == 0
  ignore_errors: true
- name: docker remove containers
  shell: docker rm $(docker ps -aq)
  when: containers_running.rc == 0
  ignore_errors: true

- name: docker build
  vars:
    _docker_app_name: app
  shell:
    cmd: docker build -f Dockerfile -t "{{ docker_app_name | default(_docker_app_name) }}" .
    chdir: '{{ dest_dir }}'
- name: docker run app
  vars:
    _docker_app_name: app
  shell: |
    docker run \
    --restart always \
    -p 3000:3000 \
    -e PORT=3000 \
    -d "{{ docker_app_name | default(_docker_app_name) }}"

- name: docker run kafka
  shell: |
    docker run -d --name kafka \
    --hostname="{{ ansible_default_ipv4.address }}" \
    -e KAFKA_CFG_NODE_ID=0 \
    -e KAFKA_CFG_PROCESS_ROLES=controller,broker \
    -e KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093 \
    -e KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT \
    -e KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@//:9093 \
    -e KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER \
    -e KAFKA_ADVERTISED_HOST_NAME="{{ ansible_default_ipv4.address }}" \
    -p 9092:9092 \
    -p 9093:9093 \
    bitnami/kafka:latest
